import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'
import tailwindForms from '@tailwindcss/forms'

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        editor: {
          bg: '#ffffff',
          'bg-dark': '#1a1a1a',
          paper: '#f9fafb',
          'paper-dark': '#262626',
          border: '#e5e7eb',
          'border-dark': '#404040',
          text: '#111827',
          'text-dark': '#f3f4f6',
          'text-muted': '#6b7280',
          'text-muted-dark': '#9ca3af',
        },
        toolbar: {
          bg: '#f3f4f6',
          'bg-dark': '#262626',
          'hover-bg': '#e5e7eb',
          'hover-bg-dark': '#404040',
          'active-bg': '#dbeafe',
          'active-bg-dark': '#1e3a8a',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        mono: [
          '"Fira Code"',
          '"Courier New"',
          'Courier',
          'monospace',
        ],
        editor: [
          'Arial',
          '"Segoe UI"',
          '"Times New Roman"',
          'Georgia',
          'Calibri',
          'Verdana',
          'Helvetica',
          'sans-serif',
        ],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '18': '4.5rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        'toolbar': '3rem',
        'statusbar': '1.75rem',
        'sidebar': '16rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'DEFAULT': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        'inner': 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
        'toolbar': '0 1px 3px 0 rgb(0 0 0 / 0.1)',
        'dialog': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'page': '0 4px 6px -1px rgb(0 0 0 / 0.05)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in',
        'fade-out': 'fadeOut 0.2s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'slide-left': 'slideLeft 0.2s ease-out',
        'slide-right': 'slideRight 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-out',
        'spin-slow': 'spin 3s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
      zIndex: {
        '0': '0',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        'dropdown': '100',
        'sticky': '200',
        'toolbar': '300',
        'overlay': '400',
        'modal': '500',
        'popover': '600',
        'tooltip': '700',
        'toast': '800',
        'max': '9999',
      },
      maxWidth: {
        'page-a4': '794px',
        'page-letter': '813px',
        'editor': '1200px',
        'toolbar': '100%',
      },
      minHeight: {
        'toolbar': '3rem',
        'statusbar': '1.75rem',
        'page': '1123px',
      },
    },
  },
  plugins: [
    plugin(function({ addUtilities, addComponents }) {
      addUtilities({
        '.scrollbar-thin': {
          'scrollbar-width': 'thin',
        },
        '.scrollbar-none': {
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
        '.text-balance': {
          'text-wrap': 'balance',
        },
        '.text-pretty': {
          'text-wrap': 'pretty',
        },
      })

      addComponents({
        '.toolbar-button': {
          '@apply inline-flex items-center justify-center rounded-md px-2 py-1.5': {},
          '@apply text-sm font-medium transition-colors': {},
          '@apply hover:bg-toolbar-hover-bg dark:hover:bg-toolbar-hover-bg-dark': {},
          '@apply focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2': {},
          '@apply disabled:opacity-50 disabled:cursor-not-allowed': {},
        },
        '.toolbar-button-active': {
          '@apply bg-toolbar-active-bg dark:bg-toolbar-active-bg-dark': {},
          '@apply text-primary-700 dark:text-primary-300': {},
        },
        '.editor-input': {
          '@apply w-full rounded-md border border-editor-border dark:border-editor-border-dark': {},
          '@apply bg-editor-bg dark:bg-editor-bg-dark': {},
          '@apply px-3 py-2 text-sm': {},
          '@apply placeholder:text-editor-text-muted dark:placeholder:text-editor-text-muted-dark': {},
          '@apply focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent': {},
          '@apply disabled:cursor-not-allowed disabled:opacity-50': {},
        },
        '.editor-select': {
          '@apply w-full rounded-md border border-editor-border dark:border-editor-border-dark': {},
          '@apply bg-editor-bg dark:bg-editor-bg-dark': {},
          '@apply px-3 py-2 pr-10 text-sm': {},
          '@apply focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent': {},
          '@apply disabled:cursor-not-allowed disabled:opacity-50': {},
        },
        '.editor-dialog': {
          '@apply fixed inset-0 z-modal': {},
          '@apply flex items-center justify-center p-4': {},
          '@apply bg-black/50 backdrop-blur-sm': {},
        },
        '.editor-dialog-content': {
          '@apply relative bg-editor-bg dark:bg-editor-bg-dark': {},
          '@apply rounded-lg shadow-dialog': {},
          '@apply max-w-lg w-full p-6': {},
          '@apply animate-scale-in': {},
        },
        '.editor-dropdown': {
          '@apply absolute z-dropdown': {},
          '@apply min-w-[12rem] rounded-md': {},
          '@apply bg-editor-bg dark:bg-editor-bg-dark': {},
          '@apply border border-editor-border dark:border-editor-border-dark': {},
          '@apply shadow-lg': {},
          '@apply animate-slide-down': {},
        },
        '.editor-tooltip': {
          '@apply absolute z-tooltip': {},
          '@apply px-2 py-1 rounded': {},
          '@apply bg-gray-900 dark:bg-gray-700': {},
          '@apply text-xs text-white': {},
          '@apply whitespace-nowrap': {},
          '@apply pointer-events-none': {},
        },
        '.page-container': {
          '@apply mx-auto bg-editor-paper dark:bg-editor-paper-dark': {},
          '@apply shadow-page': {},
          '@apply min-h-page': {},
        },
        '.canvas-wrapper': {
          '@apply relative w-full h-full': {},
          '@apply bg-editor-bg dark:bg-editor-bg-dark': {},
        },
      })
    }),
    tailwindForms({
      strategy: 'class',
    }),
  ],
}

export default config
